# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cravings' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cravings
  pod 'react-native-camera', path: '../node_modules/react-native-camera'

  target 'cravingsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'cravings-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cravings-tvOS

  target 'cravings-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
